name: Update README

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get SVG image from API
        id: get_svg
        run: |
          SVG=$(curl -s -H "Authorization: Bearer ${{ secrets.README_WORKFLOW }}" https://stdstatistics.onrender.com/generate-svg?username=whatever)
          echo "::set-output name=svg::$SVG"

      - name: Update README.md
        run: |
          echo "$(steps.get_svg.outputs.svg)" > README.md
