name: Update SVG in README.md

on:
  schedule:
    - cron:  '0 * * * *' 

jobs:
  update-svg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get SVG from API
        id: get_svg
        run: |
          SVG=$(curl -s https://stdstatistics.onrender.com/generate-svg?username=whatever)
          echo "::set-output name=svg::$SVG"

      - name: Update README.md
        run: |
          echo "$(echo $SVG | sed 's/&/\&amp;/g' | sed 's/</\&lt;/g' | sed 's/>/\&gt;/g')" > README.md
          git config --local user.email "whatever@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update SVG in README.md"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.README_WORKFLOW}}
