name: Update README

on:
  schedule:
    - cron: '0 * * * *'  # Это cron выражение запускает workflow каждый час
  push:
    branches:
      - main  # Выполнение при каждом push на ветку main
  workflow_dispatch:  # Позволяет запускать workflow вручную

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch SVG from API
      run: |
        temp_filename=$(mktemp).csv
        mkdir -p img
        img_dir=$(realpath img)
        curl -o ${temp_filename} "https://stdstatistics.onrender.com/generate-svg?username=whatever"
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        mv ${temp_filename} ${img_dir}/
        
    - name: Display directory contents for debugging
      run: ls -R
   
    - name: Commit new SVG
      run: |
        git add img/${temp_filename}
        git diff-index --quiet HEAD || git commit -m 'Update SVG image'
      env:
        GITHUB_TOKEN: ${{ secrets.README_WORKFLOW }}

    - name: Update README
      run: |
        sed -i.bak "s|!\[Dynamic SVG Image\]\(.*\)|![Dynamic SVG Image](${img_path})|" README.md
        git add README.md
        git diff-index --quiet HEAD || git commit -m 'Update README with new SVG'
      env:
        GITHUB_TOKEN: ${{ secrets.README_WORKFLOW }}

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.README_WORKFLOW }}
      run: |
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
        git push origin HEAD:main
